apiVersion: v1
kind: Service
metadata:
  labels:
    app: node0
  name: node0
spec:
  clusterIP: None
  ports:
  - name: p2p-net-port
    port: 26656
  - name: prometheus
    port: 26660
  selector:
    app: node0