{
 "title": "Execution Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Network",
    "query": "label_values(ledger_log_messages_total,kubernetes_namespace)"
   },
   {
    "name": "Node",
    "query": "label_values(ledger_log_messages_total{kubernetes_namespace=\"$Network\"},app)"
   }
  ]
 },
 "panels": [
  {
   "title": "Execution Overview",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(ledger_executor_tx_retrieve_duration_sum{app=\"$Node\", kubernetes_namespace=\"$Network\"}[100s])",
     "legendFormat": "Tx Retrieve"
    },
    {
     "expr": "delta(ledger_executor_validation_checks_duration_sum{app=\"$Node\", kubernetes_namespace=\"$Network\"}[100s])",
     "legendFormat": "Validation Checks"
    },
    {
     "expr": "delta(ledger_executor_contract_execution_duration_sum{app=\"$Node\", kubernetes_namespace=\"$Network\"}[100s])",
     "legendFormat": "Contract Execution"
    },
    {
     "expr": "delta(ledger_executor_transfers_duration_sum{app=\"$Node\", kubernetes_namespace=\"$Network\"}[100s])",
     "legendFormat": "Transfers"
    },
    {
     "expr": "delta(ledger_executor_deduct_fees_duration_sum{app=\"$Node\", kubernetes_namespace=\"$Network\"}[100s])",
     "legendFormat": "Fee Deduction"
    },
    {
     "expr": "delta(ledger_executor_settle_fees_duration_sum{app=\"$Node\", kubernetes_namespace=\"$Network\"}[100s])",
     "legendFormat": "Fee Settlement"
    }
   ]
  },
  {
   "title": "Overall Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "ledger_executor_overall_duration_bucket{app=\"$Node\",kubernetes_namespace=\"$Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TX Retrieval Time",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ledger_executor_tx_retrieve_duration_bucket{app=\"$Node\",kubernetes_namespace=\"$Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Validation Checks Time",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "ledger_executor_validation_checks_duration_bucket{app=\"$Node\",kubernetes_namespace=\"$Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Contract Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "ledger_executor_contract_execution_duration_bucket{app=\"$Node\",kubernetes_namespace=\"$Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transfers Time",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "ledger_executor_transfers_duration_bucket{app=\"$Node\",kubernetes_namespace=\"$Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Deduct Fees Time",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "ledger_executor_deduct_fees_duration_bucket{app=\"$Node\",kubernetes_namespace=\"$Network\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}