apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        - name: ledger
          image: prom/prometheus

          args:
            - "--config.file=/etc/config/prom"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"

          ports:
            - name: http
              containerPort: 9090

          volumeMounts:
          - name: config-volume
            mountPath: /etc/config

          # moderate requirements
          resources:
            requests:
              cpu: 1500m
              memory: 2Gi


      volumes:
        - name: config-volume
          configMap:
            name: prom-cfg
