// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/types/evidence.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	keys "github.com/tendermint/tendermint/proto/crypto/keys"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DuplicateVoteEvidence contains evidence a validator signed two conflicting
// votes.
type DuplicateVoteEvidence struct {
	PubKey               *keys.PublicKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	VoteA                *Vote           `protobuf:"bytes,2,opt,name=vote_a,json=voteA,proto3" json:"vote_a,omitempty"`
	VoteB                *Vote           `protobuf:"bytes,3,opt,name=vote_b,json=voteB,proto3" json:"vote_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DuplicateVoteEvidence) Reset()         { *m = DuplicateVoteEvidence{} }
func (m *DuplicateVoteEvidence) String() string { return proto.CompactTextString(m) }
func (*DuplicateVoteEvidence) ProtoMessage()    {}
func (*DuplicateVoteEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{0}
}
func (m *DuplicateVoteEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateVoteEvidence.Unmarshal(m, b)
}
func (m *DuplicateVoteEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateVoteEvidence.Marshal(b, m, deterministic)
}
func (m *DuplicateVoteEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateVoteEvidence.Merge(m, src)
}
func (m *DuplicateVoteEvidence) XXX_Size() int {
	return xxx_messageInfo_DuplicateVoteEvidence.Size(m)
}
func (m *DuplicateVoteEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateVoteEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateVoteEvidence proto.InternalMessageInfo

func (m *DuplicateVoteEvidence) GetPubKey() *keys.PublicKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *DuplicateVoteEvidence) GetVoteA() *Vote {
	if m != nil {
		return m.VoteA
	}
	return nil
}

func (m *DuplicateVoteEvidence) GetVoteB() *Vote {
	if m != nil {
		return m.VoteB
	}
	return nil
}

type PotentialAmnesiaEvidence struct {
	VoteA                *Vote    `protobuf:"bytes,1,opt,name=vote_a,json=voteA,proto3" json:"vote_a,omitempty"`
	VoteB                *Vote    `protobuf:"bytes,2,opt,name=vote_b,json=voteB,proto3" json:"vote_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PotentialAmnesiaEvidence) Reset()         { *m = PotentialAmnesiaEvidence{} }
func (m *PotentialAmnesiaEvidence) String() string { return proto.CompactTextString(m) }
func (*PotentialAmnesiaEvidence) ProtoMessage()    {}
func (*PotentialAmnesiaEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{1}
}
func (m *PotentialAmnesiaEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotentialAmnesiaEvidence.Unmarshal(m, b)
}
func (m *PotentialAmnesiaEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotentialAmnesiaEvidence.Marshal(b, m, deterministic)
}
func (m *PotentialAmnesiaEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotentialAmnesiaEvidence.Merge(m, src)
}
func (m *PotentialAmnesiaEvidence) XXX_Size() int {
	return xxx_messageInfo_PotentialAmnesiaEvidence.Size(m)
}
func (m *PotentialAmnesiaEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_PotentialAmnesiaEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_PotentialAmnesiaEvidence proto.InternalMessageInfo

func (m *PotentialAmnesiaEvidence) GetVoteA() *Vote {
	if m != nil {
		return m.VoteA
	}
	return nil
}

func (m *PotentialAmnesiaEvidence) GetVoteB() *Vote {
	if m != nil {
		return m.VoteB
	}
	return nil
}

// MockEvidence is used for testing pruposes
type MockEvidence struct {
	EvidenceHeight       int64     `protobuf:"varint,1,opt,name=evidence_height,json=evidenceHeight,proto3" json:"evidence_height,omitempty"`
	EvidenceTime         time.Time `protobuf:"bytes,2,opt,name=evidence_time,json=evidenceTime,proto3,stdtime" json:"evidence_time"`
	EvidenceAddress      []byte    `protobuf:"bytes,3,opt,name=evidence_address,json=evidenceAddress,proto3" json:"evidence_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MockEvidence) Reset()         { *m = MockEvidence{} }
func (m *MockEvidence) String() string { return proto.CompactTextString(m) }
func (*MockEvidence) ProtoMessage()    {}
func (*MockEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{2}
}
func (m *MockEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockEvidence.Unmarshal(m, b)
}
func (m *MockEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockEvidence.Marshal(b, m, deterministic)
}
func (m *MockEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockEvidence.Merge(m, src)
}
func (m *MockEvidence) XXX_Size() int {
	return xxx_messageInfo_MockEvidence.Size(m)
}
func (m *MockEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MockEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MockEvidence proto.InternalMessageInfo

func (m *MockEvidence) GetEvidenceHeight() int64 {
	if m != nil {
		return m.EvidenceHeight
	}
	return 0
}

func (m *MockEvidence) GetEvidenceTime() time.Time {
	if m != nil {
		return m.EvidenceTime
	}
	return time.Time{}
}

func (m *MockEvidence) GetEvidenceAddress() []byte {
	if m != nil {
		return m.EvidenceAddress
	}
	return nil
}

type MockRandomEvidence struct {
	EvidenceHeight       int64     `protobuf:"varint,1,opt,name=evidence_height,json=evidenceHeight,proto3" json:"evidence_height,omitempty"`
	EvidenceTime         time.Time `protobuf:"bytes,2,opt,name=evidence_time,json=evidenceTime,proto3,stdtime" json:"evidence_time"`
	EvidenceAddress      []byte    `protobuf:"bytes,3,opt,name=evidence_address,json=evidenceAddress,proto3" json:"evidence_address,omitempty"`
	RandBytes            []byte    `protobuf:"bytes,4,opt,name=rand_bytes,json=randBytes,proto3" json:"rand_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MockRandomEvidence) Reset()         { *m = MockRandomEvidence{} }
func (m *MockRandomEvidence) String() string { return proto.CompactTextString(m) }
func (*MockRandomEvidence) ProtoMessage()    {}
func (*MockRandomEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{3}
}
func (m *MockRandomEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MockRandomEvidence.Unmarshal(m, b)
}
func (m *MockRandomEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MockRandomEvidence.Marshal(b, m, deterministic)
}
func (m *MockRandomEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MockRandomEvidence.Merge(m, src)
}
func (m *MockRandomEvidence) XXX_Size() int {
	return xxx_messageInfo_MockRandomEvidence.Size(m)
}
func (m *MockRandomEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MockRandomEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MockRandomEvidence proto.InternalMessageInfo

func (m *MockRandomEvidence) GetEvidenceHeight() int64 {
	if m != nil {
		return m.EvidenceHeight
	}
	return 0
}

func (m *MockRandomEvidence) GetEvidenceTime() time.Time {
	if m != nil {
		return m.EvidenceTime
	}
	return time.Time{}
}

func (m *MockRandomEvidence) GetEvidenceAddress() []byte {
	if m != nil {
		return m.EvidenceAddress
	}
	return nil
}

func (m *MockRandomEvidence) GetRandBytes() []byte {
	if m != nil {
		return m.RandBytes
	}
	return nil
}

type ConflictingHeadersEvidence struct {
	H1                   *SignedHeader `protobuf:"bytes,1,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   *SignedHeader `protobuf:"bytes,2,opt,name=h2,proto3" json:"h2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConflictingHeadersEvidence) Reset()         { *m = ConflictingHeadersEvidence{} }
func (m *ConflictingHeadersEvidence) String() string { return proto.CompactTextString(m) }
func (*ConflictingHeadersEvidence) ProtoMessage()    {}
func (*ConflictingHeadersEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{4}
}
func (m *ConflictingHeadersEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConflictingHeadersEvidence.Unmarshal(m, b)
}
func (m *ConflictingHeadersEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConflictingHeadersEvidence.Marshal(b, m, deterministic)
}
func (m *ConflictingHeadersEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConflictingHeadersEvidence.Merge(m, src)
}
func (m *ConflictingHeadersEvidence) XXX_Size() int {
	return xxx_messageInfo_ConflictingHeadersEvidence.Size(m)
}
func (m *ConflictingHeadersEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_ConflictingHeadersEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_ConflictingHeadersEvidence proto.InternalMessageInfo

func (m *ConflictingHeadersEvidence) GetH1() *SignedHeader {
	if m != nil {
		return m.H1
	}
	return nil
}

func (m *ConflictingHeadersEvidence) GetH2() *SignedHeader {
	if m != nil {
		return m.H2
	}
	return nil
}

type LunaticValidatorEvidence struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Vote                 *Vote    `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`
	InvalidHeaderField   string   `protobuf:"bytes,3,opt,name=invalid_header_field,json=invalidHeaderField,proto3" json:"invalid_header_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LunaticValidatorEvidence) Reset()         { *m = LunaticValidatorEvidence{} }
func (m *LunaticValidatorEvidence) String() string { return proto.CompactTextString(m) }
func (*LunaticValidatorEvidence) ProtoMessage()    {}
func (*LunaticValidatorEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{5}
}
func (m *LunaticValidatorEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LunaticValidatorEvidence.Unmarshal(m, b)
}
func (m *LunaticValidatorEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LunaticValidatorEvidence.Marshal(b, m, deterministic)
}
func (m *LunaticValidatorEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LunaticValidatorEvidence.Merge(m, src)
}
func (m *LunaticValidatorEvidence) XXX_Size() int {
	return xxx_messageInfo_LunaticValidatorEvidence.Size(m)
}
func (m *LunaticValidatorEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_LunaticValidatorEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_LunaticValidatorEvidence proto.InternalMessageInfo

func (m *LunaticValidatorEvidence) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *LunaticValidatorEvidence) GetVote() *Vote {
	if m != nil {
		return m.Vote
	}
	return nil
}

func (m *LunaticValidatorEvidence) GetInvalidHeaderField() string {
	if m != nil {
		return m.InvalidHeaderField
	}
	return ""
}

type BeaconInactivityEvidence struct {
	EvidenceHeight       int64     `protobuf:"varint,1,opt,name=evidence_height,json=evidenceHeight,proto3" json:"evidence_height,omitempty"`
	EvidenceTime         time.Time `protobuf:"bytes,2,opt,name=evidence_time,json=evidenceTime,proto3,stdtime" json:"evidence_time"`
	DefendantAddress     []byte    `protobuf:"bytes,3,opt,name=defendant_address,json=defendantAddress,proto3" json:"defendant_address,omitempty"`
	ComplainantAddress   []byte    `protobuf:"bytes,4,opt,name=complainant_address,json=complainantAddress,proto3" json:"complainant_address,omitempty"`
	AeonStart            int64     `protobuf:"varint,5,opt,name=aeon_start,json=aeonStart,proto3" json:"aeon_start,omitempty"`
	ComplainantSignature []byte    `protobuf:"bytes,6,opt,name=complainant_signature,json=complainantSignature,proto3" json:"complainant_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BeaconInactivityEvidence) Reset()         { *m = BeaconInactivityEvidence{} }
func (m *BeaconInactivityEvidence) String() string { return proto.CompactTextString(m) }
func (*BeaconInactivityEvidence) ProtoMessage()    {}
func (*BeaconInactivityEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{6}
}
func (m *BeaconInactivityEvidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeaconInactivityEvidence.Unmarshal(m, b)
}
func (m *BeaconInactivityEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeaconInactivityEvidence.Marshal(b, m, deterministic)
}
func (m *BeaconInactivityEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeaconInactivityEvidence.Merge(m, src)
}
func (m *BeaconInactivityEvidence) XXX_Size() int {
	return xxx_messageInfo_BeaconInactivityEvidence.Size(m)
}
func (m *BeaconInactivityEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_BeaconInactivityEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_BeaconInactivityEvidence proto.InternalMessageInfo

func (m *BeaconInactivityEvidence) GetEvidenceHeight() int64 {
	if m != nil {
		return m.EvidenceHeight
	}
	return 0
}

func (m *BeaconInactivityEvidence) GetEvidenceTime() time.Time {
	if m != nil {
		return m.EvidenceTime
	}
	return time.Time{}
}

func (m *BeaconInactivityEvidence) GetDefendantAddress() []byte {
	if m != nil {
		return m.DefendantAddress
	}
	return nil
}

func (m *BeaconInactivityEvidence) GetComplainantAddress() []byte {
	if m != nil {
		return m.ComplainantAddress
	}
	return nil
}

func (m *BeaconInactivityEvidence) GetAeonStart() int64 {
	if m != nil {
		return m.AeonStart
	}
	return 0
}

func (m *BeaconInactivityEvidence) GetComplainantSignature() []byte {
	if m != nil {
		return m.ComplainantSignature
	}
	return nil
}

type Evidence struct {
	// Types that are valid to be assigned to Sum:
	//	*Evidence_DuplicateVoteEvidence
	//	*Evidence_ConflictingHeadersEvidence
	//	*Evidence_LunaticValidatorEvidence
	//	*Evidence_PotentialAmnesiaEvidence
	//	*Evidence_MockEvidence
	//	*Evidence_MockRandomEvidence
	//	*Evidence_BeaconInactivityEvidence
	Sum                  isEvidence_Sum `protobuf_oneof:"sum"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Evidence) Reset()         { *m = Evidence{} }
func (m *Evidence) String() string { return proto.CompactTextString(m) }
func (*Evidence) ProtoMessage()    {}
func (*Evidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{7}
}
func (m *Evidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Evidence.Unmarshal(m, b)
}
func (m *Evidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Evidence.Marshal(b, m, deterministic)
}
func (m *Evidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Evidence.Merge(m, src)
}
func (m *Evidence) XXX_Size() int {
	return xxx_messageInfo_Evidence.Size(m)
}
func (m *Evidence) XXX_DiscardUnknown() {
	xxx_messageInfo_Evidence.DiscardUnknown(m)
}

var xxx_messageInfo_Evidence proto.InternalMessageInfo

type isEvidence_Sum interface {
	isEvidence_Sum()
}

type Evidence_DuplicateVoteEvidence struct {
	DuplicateVoteEvidence *DuplicateVoteEvidence `protobuf:"bytes,1,opt,name=duplicate_vote_evidence,json=duplicateVoteEvidence,proto3,oneof" json:"duplicate_vote_evidence,omitempty"`
}
type Evidence_ConflictingHeadersEvidence struct {
	ConflictingHeadersEvidence *ConflictingHeadersEvidence `protobuf:"bytes,2,opt,name=conflicting_headers_evidence,json=conflictingHeadersEvidence,proto3,oneof" json:"conflicting_headers_evidence,omitempty"`
}
type Evidence_LunaticValidatorEvidence struct {
	LunaticValidatorEvidence *LunaticValidatorEvidence `protobuf:"bytes,3,opt,name=lunatic_validator_evidence,json=lunaticValidatorEvidence,proto3,oneof" json:"lunatic_validator_evidence,omitempty"`
}
type Evidence_PotentialAmnesiaEvidence struct {
	PotentialAmnesiaEvidence *PotentialAmnesiaEvidence `protobuf:"bytes,4,opt,name=potential_amnesia_evidence,json=potentialAmnesiaEvidence,proto3,oneof" json:"potential_amnesia_evidence,omitempty"`
}
type Evidence_MockEvidence struct {
	MockEvidence *MockEvidence `protobuf:"bytes,5,opt,name=mock_evidence,json=mockEvidence,proto3,oneof" json:"mock_evidence,omitempty"`
}
type Evidence_MockRandomEvidence struct {
	MockRandomEvidence *MockRandomEvidence `protobuf:"bytes,6,opt,name=mock_random_evidence,json=mockRandomEvidence,proto3,oneof" json:"mock_random_evidence,omitempty"`
}
type Evidence_BeaconInactivityEvidence struct {
	BeaconInactivityEvidence *BeaconInactivityEvidence `protobuf:"bytes,7,opt,name=beacon_inactivity_evidence,json=beaconInactivityEvidence,proto3,oneof" json:"beacon_inactivity_evidence,omitempty"`
}

func (*Evidence_DuplicateVoteEvidence) isEvidence_Sum()      {}
func (*Evidence_ConflictingHeadersEvidence) isEvidence_Sum() {}
func (*Evidence_LunaticValidatorEvidence) isEvidence_Sum()   {}
func (*Evidence_PotentialAmnesiaEvidence) isEvidence_Sum()   {}
func (*Evidence_MockEvidence) isEvidence_Sum()               {}
func (*Evidence_MockRandomEvidence) isEvidence_Sum()         {}
func (*Evidence_BeaconInactivityEvidence) isEvidence_Sum()   {}

func (m *Evidence) GetSum() isEvidence_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Evidence) GetDuplicateVoteEvidence() *DuplicateVoteEvidence {
	if x, ok := m.GetSum().(*Evidence_DuplicateVoteEvidence); ok {
		return x.DuplicateVoteEvidence
	}
	return nil
}

func (m *Evidence) GetConflictingHeadersEvidence() *ConflictingHeadersEvidence {
	if x, ok := m.GetSum().(*Evidence_ConflictingHeadersEvidence); ok {
		return x.ConflictingHeadersEvidence
	}
	return nil
}

func (m *Evidence) GetLunaticValidatorEvidence() *LunaticValidatorEvidence {
	if x, ok := m.GetSum().(*Evidence_LunaticValidatorEvidence); ok {
		return x.LunaticValidatorEvidence
	}
	return nil
}

func (m *Evidence) GetPotentialAmnesiaEvidence() *PotentialAmnesiaEvidence {
	if x, ok := m.GetSum().(*Evidence_PotentialAmnesiaEvidence); ok {
		return x.PotentialAmnesiaEvidence
	}
	return nil
}

func (m *Evidence) GetMockEvidence() *MockEvidence {
	if x, ok := m.GetSum().(*Evidence_MockEvidence); ok {
		return x.MockEvidence
	}
	return nil
}

func (m *Evidence) GetMockRandomEvidence() *MockRandomEvidence {
	if x, ok := m.GetSum().(*Evidence_MockRandomEvidence); ok {
		return x.MockRandomEvidence
	}
	return nil
}

func (m *Evidence) GetBeaconInactivityEvidence() *BeaconInactivityEvidence {
	if x, ok := m.GetSum().(*Evidence_BeaconInactivityEvidence); ok {
		return x.BeaconInactivityEvidence
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Evidence) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Evidence_DuplicateVoteEvidence)(nil),
		(*Evidence_ConflictingHeadersEvidence)(nil),
		(*Evidence_LunaticValidatorEvidence)(nil),
		(*Evidence_PotentialAmnesiaEvidence)(nil),
		(*Evidence_MockEvidence)(nil),
		(*Evidence_MockRandomEvidence)(nil),
		(*Evidence_BeaconInactivityEvidence)(nil),
	}
}

// EvidenceData contains any evidence of malicious wrong-doing by validators
type EvidenceData struct {
	Evidence             []Evidence `protobuf:"bytes,1,rep,name=evidence,proto3" json:"evidence"`
	Hash                 []byte     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EvidenceData) Reset()         { *m = EvidenceData{} }
func (m *EvidenceData) String() string { return proto.CompactTextString(m) }
func (*EvidenceData) ProtoMessage()    {}
func (*EvidenceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{8}
}
func (m *EvidenceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvidenceData.Unmarshal(m, b)
}
func (m *EvidenceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvidenceData.Marshal(b, m, deterministic)
}
func (m *EvidenceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvidenceData.Merge(m, src)
}
func (m *EvidenceData) XXX_Size() int {
	return xxx_messageInfo_EvidenceData.Size(m)
}
func (m *EvidenceData) XXX_DiscardUnknown() {
	xxx_messageInfo_EvidenceData.DiscardUnknown(m)
}

var xxx_messageInfo_EvidenceData proto.InternalMessageInfo

func (m *EvidenceData) GetEvidence() []Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *EvidenceData) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type ProofOfLockChange struct {
	Votes                []Vote         `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes"`
	PubKey               keys.PublicKey `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProofOfLockChange) Reset()         { *m = ProofOfLockChange{} }
func (m *ProofOfLockChange) String() string { return proto.CompactTextString(m) }
func (*ProofOfLockChange) ProtoMessage()    {}
func (*ProofOfLockChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_86495eef24aeacc0, []int{9}
}
func (m *ProofOfLockChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofOfLockChange.Unmarshal(m, b)
}
func (m *ProofOfLockChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofOfLockChange.Marshal(b, m, deterministic)
}
func (m *ProofOfLockChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofOfLockChange.Merge(m, src)
}
func (m *ProofOfLockChange) XXX_Size() int {
	return xxx_messageInfo_ProofOfLockChange.Size(m)
}
func (m *ProofOfLockChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofOfLockChange.DiscardUnknown(m)
}

var xxx_messageInfo_ProofOfLockChange proto.InternalMessageInfo

func (m *ProofOfLockChange) GetVotes() []Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *ProofOfLockChange) GetPubKey() keys.PublicKey {
	if m != nil {
		return m.PubKey
	}
	return keys.PublicKey{}
}

func init() {
	proto.RegisterType((*DuplicateVoteEvidence)(nil), "tendermint.proto.types.DuplicateVoteEvidence")
	proto.RegisterType((*PotentialAmnesiaEvidence)(nil), "tendermint.proto.types.PotentialAmnesiaEvidence")
	proto.RegisterType((*MockEvidence)(nil), "tendermint.proto.types.MockEvidence")
	proto.RegisterType((*MockRandomEvidence)(nil), "tendermint.proto.types.MockRandomEvidence")
	proto.RegisterType((*ConflictingHeadersEvidence)(nil), "tendermint.proto.types.ConflictingHeadersEvidence")
	proto.RegisterType((*LunaticValidatorEvidence)(nil), "tendermint.proto.types.LunaticValidatorEvidence")
	proto.RegisterType((*BeaconInactivityEvidence)(nil), "tendermint.proto.types.BeaconInactivityEvidence")
	proto.RegisterType((*Evidence)(nil), "tendermint.proto.types.Evidence")
	proto.RegisterType((*EvidenceData)(nil), "tendermint.proto.types.EvidenceData")
	proto.RegisterType((*ProofOfLockChange)(nil), "tendermint.proto.types.ProofOfLockChange")
}

func init() { proto.RegisterFile("proto/types/evidence.proto", fileDescriptor_86495eef24aeacc0) }

var fileDescriptor_86495eef24aeacc0 = []byte{
	// 900 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x4d, 0x8f, 0xdb, 0x44,
	0x18, 0x8e, 0xb3, 0x49, 0xba, 0xfb, 0x36, 0x85, 0x76, 0xd8, 0xa5, 0x96, 0xd5, 0xb2, 0x95, 0x85,
	0x68, 0xf9, 0x72, 0xb6, 0x59, 0x84, 0x38, 0xb2, 0x69, 0xa9, 0x52, 0x6d, 0x11, 0x2b, 0x2f, 0xea,
	0x81, 0x03, 0xd6, 0xd8, 0x9e, 0xd8, 0xa3, 0xd8, 0x33, 0x96, 0x3d, 0x8e, 0xe4, 0x3b, 0x07, 0x8e,
	0x5c, 0xf8, 0x19, 0x5c, 0x39, 0x23, 0x71, 0xe1, 0xcc, 0x0f, 0x80, 0x5f, 0xc1, 0x1d, 0x79, 0xc6,
	0x5f, 0x65, 0xd7, 0x51, 0xe0, 0x82, 0x7a, 0x89, 0x9c, 0xf7, 0xe3, 0x79, 0xde, 0x99, 0xf7, 0x99,
	0x77, 0x06, 0x8c, 0x24, 0xe5, 0x82, 0xcf, 0x44, 0x91, 0x90, 0x6c, 0x46, 0x36, 0xd4, 0x27, 0xcc,
	0x23, 0x96, 0x34, 0xa2, 0xb7, 0x05, 0x61, 0x3e, 0x49, 0x63, 0xca, 0x84, 0xb2, 0x58, 0x32, 0xcc,
	0x78, 0x4f, 0x84, 0x34, 0xf5, 0x9d, 0x04, 0xa7, 0xa2, 0x98, 0xa9, 0xfc, 0x80, 0x07, 0xbc, 0xfd,
	0x52, 0xd1, 0xc6, 0xdd, 0x2e, 0xb6, 0xfc, 0xad, 0x1c, 0xc7, 0x01, 0xe7, 0x41, 0x44, 0x54, 0xae,
	0x9b, 0xaf, 0x66, 0x82, 0xc6, 0x24, 0x13, 0x38, 0x4e, 0xaa, 0x80, 0xfb, 0x2a, 0xd3, 0x4b, 0x8b,
	0x44, 0xf0, 0xd9, 0x9a, 0x14, 0xaf, 0xe4, 0x9b, 0xbf, 0x6a, 0x70, 0xf4, 0x34, 0x4f, 0x22, 0xea,
	0x61, 0x41, 0x5e, 0x72, 0x41, 0xbe, 0xa8, 0x0a, 0x47, 0x9f, 0xc3, 0x8d, 0x24, 0x77, 0x9d, 0x35,
	0x29, 0x74, 0xed, 0x81, 0xf6, 0xe8, 0xe6, 0xfc, 0xa1, 0x75, 0x65, 0x11, 0x0a, 0xd5, 0x2a, 0x51,
	0xad, 0x8b, 0xdc, 0x8d, 0xa8, 0x77, 0x4e, 0x0a, 0x7b, 0x92, 0xe4, 0xee, 0x39, 0x29, 0xd0, 0x29,
	0x4c, 0x36, 0x5c, 0x10, 0x07, 0xeb, 0x43, 0x09, 0x70, 0xcf, 0xba, 0x7e, 0x17, 0xac, 0x92, 0xd7,
	0x1e, 0x97, 0xb1, 0x67, 0x4d, 0x92, 0xab, 0xef, 0xed, 0x9a, 0xb4, 0x30, 0xbf, 0xd3, 0x40, 0xbf,
	0xe0, 0x82, 0x30, 0x41, 0x71, 0x74, 0x16, 0x33, 0x92, 0x51, 0xdc, 0x2c, 0xa4, 0x2d, 0x43, 0xfb,
	0x2f, 0x65, 0x0c, 0x77, 0x2f, 0xe3, 0x27, 0x0d, 0xa6, 0x5f, 0x72, 0x6f, 0xdd, 0x50, 0x3f, 0x84,
	0x37, 0x6b, 0x21, 0x38, 0x21, 0xa1, 0x41, 0x28, 0x64, 0x0d, 0x7b, 0xf6, 0x1b, 0xb5, 0x79, 0x29,
	0xad, 0xe8, 0x39, 0xdc, 0x6a, 0x02, 0xcb, 0x0e, 0x56, 0xac, 0x86, 0xa5, 0xda, 0x6b, 0xd5, 0xed,
	0xb5, 0xbe, 0xae, 0xdb, 0xbb, 0xd8, 0xff, 0xed, 0x8f, 0xe3, 0xc1, 0x0f, 0x7f, 0x1e, 0x6b, 0xf6,
	0xb4, 0x4e, 0x2d, 0x9d, 0xe8, 0x7d, 0xb8, 0xdd, 0x40, 0x61, 0xdf, 0x4f, 0x49, 0x96, 0xc9, 0xad,
	0x9c, 0xda, 0x4d, 0x2d, 0x67, 0xca, 0x6c, 0xfe, 0xae, 0x01, 0x2a, 0xeb, 0xb5, 0x31, 0xf3, 0x79,
	0xfc, 0x9a, 0x54, 0x8d, 0xee, 0x03, 0xa4, 0x98, 0xf9, 0x8e, 0x5b, 0x08, 0x92, 0xe9, 0x23, 0x19,
	0x74, 0x50, 0x5a, 0x16, 0xa5, 0xc1, 0xfc, 0x5e, 0x03, 0xe3, 0x09, 0x67, 0xab, 0x88, 0x7a, 0x82,
	0xb2, 0x60, 0x49, 0xb0, 0x4f, 0xd2, 0xac, 0x59, 0xdc, 0x27, 0x30, 0x0c, 0x1f, 0x57, 0x4a, 0x78,
	0xb7, 0xaf, 0xa9, 0x97, 0x34, 0x60, 0xc4, 0x57, 0xa9, 0xf6, 0x30, 0x7c, 0x2c, 0xb3, 0xe6, 0xd5,
	0xf2, 0x76, 0xcd, 0x9a, 0x9b, 0x3f, 0x6b, 0xa0, 0xbf, 0xc8, 0x19, 0x16, 0xd4, 0x7b, 0x89, 0x23,
	0xea, 0x63, 0xc1, 0xd3, 0xa6, 0x90, 0x4f, 0x61, 0x12, 0xca, 0xd0, 0xaa, 0x98, 0x77, 0xfa, 0x60,
	0x2b, 0xc0, 0x2a, 0x1a, 0x9d, 0xc0, 0xa8, 0x54, 0xdb, 0x4e, 0xba, 0x94, 0x91, 0xe8, 0x04, 0x0e,
	0x29, 0xdb, 0x94, 0x05, 0x38, 0x0a, 0xc3, 0x59, 0x51, 0x12, 0xf9, 0x72, 0x7f, 0x0f, 0x6c, 0x54,
	0xf9, 0x14, 0xcd, 0xb3, 0xd2, 0x63, 0xfe, 0x32, 0x04, 0x7d, 0x41, 0xb0, 0xc7, 0xd9, 0x73, 0x86,
	0x3d, 0x41, 0x37, 0x54, 0x14, 0xff, 0xab, 0x3c, 0x3e, 0x84, 0x3b, 0x3e, 0x59, 0x11, 0xe6, 0x63,
	0x26, 0xfe, 0xa1, 0x8f, 0xdb, 0x8d, 0xa3, 0x16, 0xc8, 0x0c, 0xde, 0xf2, 0x78, 0x9c, 0x44, 0x98,
	0xb2, 0x6e, 0xb8, 0x52, 0x0a, 0xea, 0xb8, 0x3a, 0x8a, 0xc2, 0x84, 0x33, 0x27, 0x13, 0x38, 0x15,
	0xfa, 0x58, 0x2e, 0xe6, 0xa0, 0xb4, 0x5c, 0x96, 0x06, 0x74, 0x0a, 0x47, 0x5d, 0xbc, 0x8c, 0x06,
	0x0c, 0x8b, 0x3c, 0x25, 0xfa, 0x44, 0x22, 0x1e, 0x76, 0x9c, 0x97, 0xb5, 0xcf, 0xfc, 0x6b, 0x0c,
	0xfb, 0xcd, 0x96, 0x05, 0x70, 0xd7, 0xaf, 0x87, 0xac, 0x23, 0xe7, 0x4a, 0xbd, 0xba, 0xaa, 0xf9,
	0x1f, 0xf7, 0xb5, 0xf1, 0xda, 0xd9, 0xbc, 0x1c, 0xd8, 0x47, 0xfe, 0xb5, 0x43, 0x7b, 0x03, 0xf7,
	0xbc, 0x56, 0xfb, 0x55, 0xbb, 0xb3, 0x96, 0x4d, 0x75, 0x60, 0xde, 0xc7, 0xd6, 0x7f, 0x6e, 0x96,
	0x03, 0xdb, 0xf0, 0xfa, 0x4f, 0x55, 0x02, 0x46, 0xa4, 0x84, 0xee, 0x6c, 0x6a, 0xa5, 0xb7, 0xac,
	0x6a, 0x92, 0x9f, 0xf4, 0xb1, 0xf6, 0x1d, 0x91, 0xe5, 0xc0, 0xd6, 0xa3, 0xbe, 0xe3, 0x93, 0x80,
	0x91, 0xd4, 0x13, 0xdf, 0xc1, 0x6a, 0xe4, 0xb7, 0x8c, 0xa3, 0xed, 0x8c, 0x7d, 0x77, 0x45, 0xc9,
	0x98, 0xf4, 0xdd, 0x23, 0xe7, 0x70, 0x2b, 0xe6, 0xde, 0xba, 0x25, 0x19, 0x6f, 0x1f, 0x07, 0xdd,
	0x9b, 0x60, 0x39, 0xb0, 0xa7, 0x71, 0xf7, 0x66, 0xf8, 0x16, 0x0e, 0x25, 0x58, 0x2a, 0x47, 0x6f,
	0x8b, 0x39, 0x91, 0x98, 0x1f, 0x6c, 0xc3, 0x7c, 0x75, 0x5a, 0x2f, 0x07, 0x36, 0x8a, 0xaf, 0xce,
	0xf0, 0x04, 0x0c, 0x57, 0x1e, 0x60, 0x87, 0x36, 0x27, 0xb8, 0x65, 0xb9, 0xb1, 0x7d, 0x7b, 0xfa,
	0x8e, 0x7e, 0xb9, 0x3d, 0x6e, 0x8f, 0x6f, 0x31, 0x86, 0xbd, 0x2c, 0x8f, 0xcd, 0x15, 0x4c, 0x6b,
	0xd3, 0x53, 0x2c, 0x30, 0x5a, 0xc0, 0x7e, 0x47, 0xeb, 0x7b, 0x8f, 0x6e, 0xce, 0x1f, 0xf4, 0xd1,
	0x36, 0x50, 0xa3, 0x72, 0x0a, 0xd8, 0x4d, 0x1e, 0x42, 0x30, 0x0a, 0x71, 0x16, 0x4a, 0xf5, 0x4e,
	0x6d, 0xf9, 0x6d, 0xfe, 0xa8, 0xc1, 0x9d, 0x8b, 0x94, 0xf3, 0xd5, 0x57, 0xab, 0x17, 0xdc, 0x5b,
	0x3f, 0x09, 0x31, 0x0b, 0x08, 0xfa, 0x0c, 0xe4, 0x55, 0x9c, 0x55, 0x54, 0x5b, 0xa7, 0x63, 0x45,
	0xa3, 0x12, 0xd0, 0xb3, 0xf6, 0xb9, 0x33, 0xfc, 0x57, 0xcf, 0x9d, 0x0a, 0xa6, 0x7a, 0xf4, 0x2c,
	0xac, 0x6f, 0x3e, 0x0a, 0xa8, 0x08, 0x73, 0xd7, 0xf2, 0x78, 0x3c, 0x6b, 0x21, 0xba, 0x9f, 0x9d,
	0xc7, 0x9c, 0x3b, 0x91, 0x7f, 0x4e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x29, 0x21, 0xf9, 0x8a,
	0x3e, 0x0a, 0x00, 0x00,
}
